hardware_bag:
  ros__parameters:
    stamp_current_date: true
    bag_name: "sensors_bag"
    topic_names:  
      ["scan",
      "hover_imu",
      "slamtec_imu",
      "joint_states",
      "hoverboard_base_controller/odom",
      "odometry/filtered",
      "tf",
      "tf_static"
      ]