#ifndef DATA_COLLECTION__HARDWARE_BAG_HPP_
#define DATA_COLLECTION__HARDWARE_BAG_HPP_


#include <memory>
#include <array>
#include <string>
#include <utility>
#include <cstdint>

#include <chrono>
#include <ctime>
#include <sstream>

#include "paxi_common/hardware_topic_names.hpp"

// auto-generated by generate_parameter_library
// see https://github.com/PickNikRobotics/generate_parameter_library
#include "paxi_data_collection/paxi_data_collection_parameters.hpp"

#include <rclcpp/rclcpp.hpp>
#include <std_msgs/msg/string.hpp>
#include "sensor_msgs/msg/laser_scan.hpp"
#include "sensor_msgs/msg/imu.hpp"
#include "sensor_msgs/msg/joint_state.hpp"
#include <rosbag2_cpp/writer.hpp>

namespace paxi_data_collection
{
class HardwareBag : public rclcpp::Node
{
public:
  HardwareBag();
  ~HardwareBag() = default;

private:
  // auto generated from paxi_data_collection_paramters
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

  const std::string get_current_date() const;

  std::unique_ptr<rosbag2_cpp::Writer> hardware_writer_;
  std::vector<rclcpp::GenericSubscription::ConstSharedPtr> subscriptions_;
};
}  // namespace paxi_data_collection

#endif  // DATA_COLLECTION__HARDWARE_BAG_HPP_
