// Copyright 2026 JustASimpleCoder
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef DATA_COLLECTION__HARDWARE_BAG_HPP_
#define DATA_COLLECTION__HARDWARE_BAG_HPP_

#include <array>
#include <chrono>
#include <cstdint>
#include <ctime>
#include <memory>
#include <sstream>
#include <string>
#include <utility>

#include "paxi_common/hardware_topic_names.hpp"

// auto-generated by generate_parameter_library
// see https://github.com/PickNikRobotics/generate_parameter_library
#include <rclcpp/rclcpp.hpp>
#include <rosbag2_cpp/writer.hpp>
#include <std_msgs/msg/string.hpp>

#include "paxi_data_collection/paxi_data_collection_parameters.hpp"
#include "sensor_msgs/msg/imu.hpp"
#include "sensor_msgs/msg/joint_state.hpp"
#include "sensor_msgs/msg/laser_scan.hpp"

namespace paxi_data_collection
{
class HardwareBag : public rclcpp::Node
{
public:
  HardwareBag();
  ~HardwareBag() = default;

  HardwareBag(const HardwareBag &) = delete;
  HardwareBag & operator=(const HardwareBag &) = delete;

  HardwareBag(HardwareBag &&) noexcept = delete;
  HardwareBag & operator=(HardwareBag &&) noexcept = delete;

private:

  const std::string get_current_date() const;

  void init_topic_info();
  void init_writer_subscribers();
  
  const std::string get_bag_name_with_stamp();

  void print_topic_added_to_bag(
    const std::string & topic_name, const rclcpp::TopicEndpointInfo & topic_endpoint);

  // auto generated from paxi_data_collection_paramters
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

  std::unique_ptr<rosbag2_cpp::Writer> hardware_writer_;
  std::vector<rclcpp::GenericSubscription::ConstSharedPtr> subscriptions_;

  std::vector<std::string> topic_names; 

  std::vector<std::vector<rclcpp::TopicEndpointInfo>> topic_endpoint_info_;
  rclcpp::TimerBase::SharedPtr init_timer_;

  std::size_t num_topics_in_params_;

  rclcpp::Time start_time_;

  static constexpr double MAX_TIME_OUT_SEC = 30;
};
}  // namespace paxi_data_collection

#endif  // DATA_COLLECTION__HARDWARE_BAG_HPP_
